### ISSUE TITLE
模型推理效果差

### ISSUE THREAD

**Issue by YaoH-N** [MengLi-l1/StrokeExtraction#8]
![Snipaste_2024-05-06_11-51-52](https://github.com/MengLi-l1/StrokeExtraction/assets/75976070/8da23980-d4a4-4127-ad88-3f5e00b2b235)
您好，我想请问您一下为什么推理代码运行的效果和训练时的效果差别这么大呀？

**Comment by MengLi-l1** [comment]
正常训练时不会有如此大的差距，你可以检查下载入模型是否正确，整个算法由三个模块构成，你的这种情况可能是某个模块模型加载失败导致的。我代码中并没有给出单独推理文件，你的推理代码是指这个吗？extraction_stroke_application_for_single_character_.py
这个文件是应部分人需求提供的一个应用代码，用于示例如何用这个算法实现对已有笔画分割需求任务的应用，你得修改下模型路径才能使用。

**Comment by YaoH-N** [comment]
> 正常训练时不会有如此大的差距，你可以检查下载入模型是否正确，整个算法由三个模块构成，你的这种情况可能是某个模块模型加载失败导致的。我代码中并没有给出单独推理文件，你的推理代码是指这个吗？extraction_stroke_application_for_single_character_.py 这个文件是应部分人需求提供的一个应用代码，用于示例如何用这个算法实现对已有笔画分割需求任务的应用，你得修改下模型路径才能使用。
![image](https://github.com/MengLi-l1/StrokeExtraction/assets/75976070/8d884a3e-7604-4f14-8c63-aa3ef476bd53)
![image](https://github.com/MengLi-l1/StrokeExtraction/assets/75976070/0182287e-f59a-4c90-ae27-e47408fa033a)

首先感谢您的回复，我用您的代码和RHSHDB数据集训练了几次，现在一直报这个错误，就是在SDNet模型epoch训练完后，执行这个代码model.calculate_prior_information_and_qualitative('dataset_forSegNet_ExtractNet_RHSEDB')计算先验信息生成供后面两个网络训练的dataset_forSegNet_ExtractNet_RHSEDB数据集时一直报这个错误是为什么呀？找了很久也没找到原因，只计算了两个之后就报错了，DeBug看了一下，好像是因为centroid_box(style[i])计算出来的point = np.where(img > 0.5) 为空，请问您遇到过这种情况吗？不知道为什么会这样，期待您的回复。

**Comment by MengLi-l1** [comment]
> > 正常训练时不会有如此大的差距，你可以检查下载入模型是否正确，整个算法由三个模块构成，你的这种情况可能是某个模块模型加载失败导致的。我代码中并没有给出单独推理文件，你的推理代码是指这个吗？extraction_stroke_application_for_single_character_.py 这个文件是应部分人需求提供的一个应用代码，用于示例如何用这个算法实现对已有笔画分割需求任务的应用，你得修改下模型路径才能使用。
> > ![image](https://private-user-images.githubusercontent.com/75976070/336730573-8d884a3e-7604-4f14-8c63-aa3ef476bd53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxOTI5MTQsIm5iZiI6MTcxODE5MjYxNCwicGF0aCI6Ii83NTk3NjA3MC8zMzY3MzA1NzMtOGQ4ODRhM2UtNzYwNC00ZjE0LThjNjMtYWEzZWY0NzZiZDUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDExNDMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5Yzg1MWQ1MDNiNzAwNGU5NjI5OGUxZWFjZGE3NWZlZjEwZjEyZGFkMGJhZWJiNjVmMDNkZGIzM2M2ZGQyNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vqy7Ao-KQJHuCVgYSJp037jo9htmS2J82e5dvtgDXAA)
> > ![image](https://private-user-images.githubusercontent.com/75976070/336731729-0182287e-f59a-4c90-ae27-e47408fa033a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxOTI5MTQsIm5iZiI6MTcxODE5MjYxNCwicGF0aCI6Ii83NTk3NjA3MC8zMzY3MzE3MjktMDE4MjI4N2UtZjU5YS00YzkwLWFlMjctZTQ3NDA4ZmEwMzNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDExNDMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhZDEzNGUyMjJhMTJiMTg3N2E4YWI5N2M3NTI1YWMxYjNhZTIwZWFiOTRjN2M5ODIxMjQ0Yjk0YTQ2ZmQ3ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JdkuBwyvV0vxxO4H51BRBuRCvpT3lq_wE1li4HXA7uQ)
> 
> 首先感谢您的回复，我用您的代码和RHSHDB数据集训练了几次，现在一直报这个错误，就是在SDNet模型epoch训练完后，执行这个代码model.calculate_prior_information_and_qualitative('dataset_forSegNet_ExtractNet_RHSEDB')计算先验信息生成供后面两个网络训练的dataset_forSegNet_ExtractNet_RHSEDB数据集时一直报这个错误是为什么呀？找了很久也没找到原因，只计算了两个之后就报错了，DeBug看了一下，好像是因为centroid_box(style[i])计算出来的point = np.where(img > 0.5) 为空，请问您遇到过这种情况吗？不知道为什么会这样，期待您的回复。

**Comment by MengLi-l1** [comment]
我看了你的报错，报错部分的调用函数如下：
![image](https://github.com/MengLi-l1/StrokeExtraction/assets/119289060/a73b95e3-d2da-4640-9314-2969f12493cd)
你的报错信息中style[i]对应的就是上述参数。也就说变换的后参考字笔画不在图像中，这种情况一种是参考字本身缺失（我检查了下没有缺失），另一种是变换后超出图像范围了。但一般变换后超出图像范围的原因是没训练好（准确说是出现异常的训练结果），一般情况不会出现这种问题，这里建议再看下SDNET的推理过程，可以可视化看下，推理过程数据集数据是顺序执行的，也可以可视化看看，如果问题依然存在，建议抛出异常并判断，直接将”低质量数据“舍弃。
